#!/usr/bin/ansible-playbook
###########################
- hosts: oo_version_3:&oo_environment_prod:&oo_master_primary
  gather_facts: false
  remote_user: root
  serial: 20

  tasks:
  - name: check-logging-es-state
    include_role:
      name: check-logging-es-state
