#!/usr/bin/ansible-playbook
###########################
- hosts: oo_version_3:&oo_environment_prod:&oo_master_primary
  gather_facts: false
  remote_user: root

  roles:
  - {role: check-oc-version,
        require_oc_version: '(3.9.41)',
    }
